import os

from dotenv import load_dotenv
from google import genai


# ---------------------------------------------------------
# Load environment variables
# ---------------------------------------------------------

load_dotenv()


API_KEY = os.getenv("GEMINI_API_KEY")

MODEL_NAME = os.getenv(
    "GEMINI_MODEL",
    "gemini-3.5-flash-lite",
)


# ---------------------------------------------------------
# Validate configuration
# ---------------------------------------------------------

if not API_KEY:
    raise ValueError(
        "GEMINI_API_KEY is missing.\n"
        "Please check your .env file."
    )


# ---------------------------------------------------------
# Gemini client
# ---------------------------------------------------------

client = genai.Client(
    api_key=API_KEY
)


# ---------------------------------------------------------
# Generate support response
# ---------------------------------------------------------

def generate_support_response(
    subject,
    body,
    category,
    priority,
    department,
    confidence,
):
    """
    Generate a professional customer support response
    using Gemini.
    """

    subject = str(subject or "").strip()
    body = str(body or "").strip()

    prompt = f"""
You are an AI customer support assistant.

Generate a professional, helpful and concise
customer support response.

CUSTOMER TICKET
----------------
Subject:
{subject}

Message:
{body}

AI ANALYSIS
----------------
Category:
{category}

Priority:
{priority}

Department:
{department}

Classification Confidence:
{confidence}%

RESPONSE REQUIREMENTS
----------------
1. Acknowledge the customer's issue.
2. Show empathy when appropriate.
3. Give a useful next step if possible.
4. Do not invent company policies, refunds,
   compensation, timelines, or technical facts.
5. Do not claim that an action has already been completed.
6. If more information is required, clearly ask for it.
7. Keep the response concise and professional.
8. Do not mention that the response was generated by AI.
9. Do not mention the internal classification system.
10. Do not expose the confidence score to the customer.

Return ONLY the customer-facing response.
"""


    # -----------------------------------------------------
    # Gemini API call
    # -----------------------------------------------------

    response = client.models.generate_content(
        model=MODEL_NAME,
        contents=prompt,
    )


    # -----------------------------------------------------
    # Validate response
    # -----------------------------------------------------

    if not response.text:
        raise RuntimeError(
            "Gemini returned an empty response."
        )


    return response.text.strip()


# ---------------------------------------------------------
# Local test
# ---------------------------------------------------------

if __name__ == "__main__":

    print("=" * 60)
    print("AI SUPPORTDESK - GEMINI RESPONSE TEST")
    print("=" * 60)

    test_subject = (
        "Payment deducted but order failed"
    )

    test_body = (
        "I placed an order and the payment "
        "was deducted from my account, but "
        "the order failed. Please help."
    )

    try:

        response = generate_support_response(
            subject=test_subject,
            body=test_body,
            category="Billing and Payments",
            priority="Critical",
            department="Billing",
            confidence=91.5,
        )

        print("\nGenerated Response:")
        print("-" * 60)
        print(response)
        print("-" * 60)

        print(
            f"\nGemini model: {MODEL_NAME}"
        )

    except Exception as error:

        print(
            "\nGemini request failed:"
        )

        print(error)